# Generated by Django 4.2.3 on 2023-07-22 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARHoldingsShopifyApp', '0002_remove_product_product_id_alter_product_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='parent',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
