# Generated by Django 4.2.3 on 2023-07-22 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ARHoldingsShopifyApp', '0004_alter_product_allow_customer_reviews_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_sale_price_ends',
        ),
        migrations.RemoveField(
            model_name='product',
            name='date_sale_price_starts',
        ),
    ]
