# Generated by Django 4.2.3 on 2023-07-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARHoldingsShopifyApp', '0005_remove_product_date_sale_price_ends_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_sale_price_ends',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='date_sale_price_starts',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
