# Generated by Django 4.2.3 on 2023-07-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARHoldingsShopifyApp', '0006_product_date_sale_price_ends_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.TextField(blank=True),
        ),
    ]
