# Generated by Django 4.2.3 on 2023-07-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARHoldingsShopifyApp', '0007_alter_product_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='synchronized_at',
            field=models.DateTimeField(null=True),
        ),
    ]
