# Generated by Django 4.2.3 on 2023-07-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARHoldingsShopifyApp', '0008_product_synchronized_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.CharField(max_length=100)),
                ('json', models.JSONField()),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
